config/routes.rb
IndianFood::Application.routes.draw do

  devise_for :users, :path => '', :path_names => { :sign_in => 'login', :sign_out => 'logout' }, :controllers => { :sessions => "sessions" }
  match "/admin" => "admin/courses#index", as: :admin

  devise_scope :user do
    get 'sign_in_modal', :to => 'sessions#sign_in_modal', :as => 'sign_in_modal'
  end

  namespace :admin do
    resources :courses do
      resources :recipes
    end

    resources :cuisines do
      resources :recipes
    end

    resources :ingredients do
      resources :recipes
    end

    resources :dishes do
      resources :recipes
    end

    resources :occassions do
      resources :recipes
    end

    resources :users do
      resources :recipes
    end
  end

  root :to => 'users#index'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IndianFood</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="header">
<div id="home_link">
  <%= link_to 'Home' %>
</div>
<div></div>
<div id="signout_link">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>.Not you?
    <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
  <% end %>
</div>
<div id="usersite_link">
  <%= button_to 'User Site', root_path %>
</div>
</div>
<p>
  <div id="notice">
    <p class="notice"><%= notice %></p>
    <p class="error"><%= flash[:error] %></p>
  </div>
</p>
<br/>
<p>
<div id="page-wrap">
<div id="banner">
  <span id="banner-heading">INDIAN FOOD</span>
  <h1 id="sub-heading"></h1>
</div>
<p id="body">
<div class="table">
  <ol id="admin-site-navigation">
    <li><%= link_to 'Recipes by courses', { :controller => "courses", :action => "index", :forrecipes => "true" }%></li>
    <li><%= link_to 'Recipes by users', {:controller => "users", :action => "index", :forrecipes => "true" }%></li>
    <li><a href="/admin/courses">Courses</a></li>
    <li><a href="#">Ingredients</a></li>
    <li><a href="#">About</a></li>
  </ol>
</div>
<div class="page">
  <div class="container-inner">
    <%= yield %>
  </div>
</div>
<div id="footer"></div>
</p>
</div>
</p>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IndianFood</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="header">
<div id="home_link">
  <%= link_to 'Home' %>
</div>
<div id="signout_link" class="links">
  <% if user_signed_in? %>
    Signed in as <%= current_user.email %>.Not you?
    <%= link_to 'Sign out', destroy_user_session_path, :method => :delete %>
  <% end %>
</div>
<div id="admin_site_link">
  <% if user_signed_in? && (current_user.has_role? :admin) %>
    <%= button_to 'Admin Site', admin_path %>
  <% end %>
</div>
<div id="signin_link" class="links">
  <% unless user_signed_in? %>
    <%= link_to 'Sign in', sign_in_modal_path, {:remote => true, 'data-toggle' => 'modal', 'data-target' => '#modal-window' }%>
  <% end %>
</div>
<%= render "devise/sessions/sign_in_modal"%>
</div>
<p>
  <div id="notice">
    <p class="notice"><%= notice %></p>
    <p class="error"><%= flash[:error] %></p>
  </div>
</p>
<br/>
<p>
<div id="page-wrap">
<div id="banner">
  <span id="banner-heading">INDIAN FOOD</span>
  <h1 id="sub-heading"></h1>
</div>
<p id="body">
<div class="table">
  <ol id="admin-site-navigation">
    <li id="recipes-by-course"><%= link_to 'Recipes by course - siteuser'%></li>
    <li><a href="#">Ingredients</a></li>
    <li><a href="#">About</a></li>
  </ol>
</div>
<div class="page">
  <div class="container-inner">
    <%= yield %>
  </div>
</div>
<div id="footer"></div>
</p>
</div>
</p>
</body>
</html>